# Generated by Django 5.1.4 on 2025-01-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('citizenship_number', models.CharField(max_length=100, unique=True)),
                ('citizenship_photo_front', models.ImageField(upload_to='citizenship_photos/front/')),
                ('citizenship_photo_back', models.ImageField(upload_to='citizenship_photos/back/')),
                ('photo', models.ImageField(upload_to='voter_photos/')),
            ],
        ),
    ]
